module.exports = {
	// Super long name prefix to avoid task name conflicts.
	// After all we need NOT to operate upon these ulgy(really?) names manually.
	namePrefixOfEveryAutoGeneratedTask: 'Wulechuan gulp 3 pipeline auto generated task:',
};